# Generated by Django 4.2.5 on 2026-02-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.IntegerField()),
                ('approach', models.IntegerField()),
                ('number_times', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeMarathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('folder', models.CharField(default='challenge-marathon', max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('man', models.BooleanField(default=False)),
                ('woman', models.BooleanField(default=False)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('desciptions', models.TextField(max_length=300)),
                ('challenges', models.ManyToManyField(related_name='marathon_challenge', to='service.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='UserSmall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('age', models.SmallIntegerField()),
                ('male', models.BooleanField()),
                ('weight', models.SmallIntegerField()),
                ('height', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MarathonDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.SmallIntegerField()),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marathon_days', to='service.challengemarathon')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeMarathonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.challengemarathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.usersmall')),
            ],
        ),
        migrations.AddField(
            model_name='challengemarathon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.usersmall'),
        ),
    ]
