# Generated by Django 4.2.5 on 2026-02-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemarathonuser',
            name='marathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marathon_user', to='service.challengemarathon'),
        ),
    ]
