# Generated by Django 4.2.5 on 2026-02-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_challengemarathonuser_marathon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengemarathon',
            name='user',
        ),
        migrations.AddField(
            model_name='challengemarathon',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
