# Generated by Django 4.2.5 on 2026-02-15 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_challengemarathon_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengemarathon',
            name='user_id',
        ),
        migrations.AddField(
            model_name='challengemarathon',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.usersmall'),
            preserve_default=False,
        ),
    ]
