# Generated by Django 4.2.5 on 2026-02-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_challengemarathon_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemarathon',
            name='callories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengemarathon',
            name='points',
            field=models.BooleanField(default=False),
        ),
    ]
