# Generated by Django 4.2.5 on 2026-02-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_challengemarathon_callories_challengemarathon_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengemarathon',
            old_name='desciptions',
            new_name='descriptions',
        ),
    ]
