# Generated by Django 4.2.5 on 2026-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_desciptions_challengemarathon_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marathondays',
            name='day_number',
        ),
        migrations.AddField(
            model_name='marathondays',
            name='challenges',
            field=models.ManyToManyField(related_name='days_challenges', to='service.challenge'),
        ),
    ]
