# Generated by Django 4.2.5 on 2026-02-17 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_marathondays_day_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarathonDayUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach', models.IntegerField(default=0)),
                ('number_times', models.IntegerField(default=0)),
                ('callories', models.DecimalField(decimal_places=2, max_digits=2)),
                ('score', models.IntegerField(default=0)),
                ('folder', models.CharField(default='')),
                ('video', models.CharField()),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marathon_day', to='service.challengemarathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marathon_day_user', to='service.usersmall')),
            ],
        ),
    ]
