# Generated by Django 4.2.5 on 2026-02-17 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_marathondayuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathondayuser',
            name='marathon_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marathon_dat_user', to='service.marathondays'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marathondayuser',
            name='callories',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
