# Generated by Django 4.2.5 on 2026-02-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_marathondayuser_marathon_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathondayuser',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('warning', 'warning')], default='warning', max_length=10),
        ),
    ]
