# Generated by Django 4.2.5 on 2026-02-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_marathondayuser_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marathondayuser',
            index=models.Index(fields=['user', 'marathon'], name='service_mar_user_id_cd6d6e_idx'),
        ),
    ]
