# Generated by Django 4.2.5 on 2026-02-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_marathondayuser_challenge'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marathondayuser',
            name='service_mar_user_id_cd6d6e_idx',
        ),
        migrations.RemoveField(
            model_name='marathondayuser',
            name='marathon',
        ),
        migrations.AddIndex(
            model_name='marathondayuser',
            index=models.Index(fields=['user', 'marathon_day'], name='service_mar_user_id_b0da45_idx'),
        ),
    ]
