# Generated by Django 4.2.5 on 2026-02-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_remove_marathondayuser_service_mar_user_id_cd6d6e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathondayuser',
            name='marathon_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marathon_day_user', to='service.marathondays'),
        ),
    ]
