# Generated by Django 4.2.5 on 2026-02-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_marathondayuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marathondayuser',
            name='approach',
        ),
    ]
