# Generated by Django 4.2.5 on 2026-02-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_remove_marathondayuser_approach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marathondayuser',
            name='status',
        ),
    ]
