# Generated by Django 4.2.5 on 2026-02-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_remove_marathondayuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marathondayuser',
            name='challenge',
        ),
    ]
