# Generated by Django 4.2.5 on 2026-02-18 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_remove_marathondayuser_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathondayuser',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marathon_user_challenge', to='service.challenge'),
            preserve_default=False,
        ),
    ]
