# Generated by Django 4.2.5 on 2026-02-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_marathondayuser_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marathondays',
            name='challenges',
        ),
    ]
