# Generated by Django 4.2.5 on 2026-02-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_remove_marathondays_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathondayuser',
            name='folder',
            field=models.CharField(default='marathon-day-user'),
        ),
    ]
