# Generated by Django 4.2.5 on 2026-02-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_alter_marathondayuser_folder'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marathondayuser',
            name='service_mar_user_id_b0da45_idx',
        ),
        migrations.AddField(
            model_name='marathondayuser',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('warning', 'warning')], default='success', max_length=10),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='marathondayuser',
            index=models.Index(fields=['user', 'marathon_day', 'challenge'], name='service_mar_user_id_cccb54_idx'),
        ),
    ]
