# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import profile_pb2 as profile__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in profile_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProfileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DataProfile = channel.unary_unary(
                '/profile.Profile/DataProfile',
                request_serializer=profile__pb2.UserID.SerializeToString,
                response_deserializer=profile__pb2.ProfileData.FromString,
                _registered_method=True)
        self.CreateProfile = channel.unary_unary(
                '/profile.Profile/CreateProfile',
                request_serializer=profile__pb2.CreateProfileData.SerializeToString,
                response_deserializer=profile__pb2.SuccessProfile.FromString,
                _registered_method=True)
        self.ProfileInfoTournament = channel.unary_unary(
                '/profile.Profile/ProfileInfoTournament',
                request_serializer=profile__pb2.UserID.SerializeToString,
                response_deserializer=profile__pb2.ProfileInfo.FromString,
                _registered_method=True)
        self.MediaProfile = channel.unary_unary(
                '/profile.Profile/MediaProfile',
                request_serializer=profile__pb2.RequestMediaProfile.SerializeToString,
                response_deserializer=profile__pb2.SuccessProfile.FromString,
                _registered_method=True)
        self.GetAdvencedMediaProfile = channel.unary_unary(
                '/profile.Profile/GetAdvencedMediaProfile',
                request_serializer=profile__pb2.GetAdvencedMedia.SerializeToString,
                response_deserializer=profile__pb2.AdvencedMediaData.FromString,
                _registered_method=True)
        self.SmallProfileInfo = channel.unary_unary(
                '/profile.Profile/SmallProfileInfo',
                request_serializer=profile__pb2.UserID.SerializeToString,
                response_deserializer=profile__pb2.SmallRequstProfile.FromString,
                _registered_method=True)
        self.DeleteAccount = channel.unary_unary(
                '/profile.Profile/DeleteAccount',
                request_serializer=profile__pb2.UserID.SerializeToString,
                response_deserializer=profile__pb2.SuccessProfile.FromString,
                _registered_method=True)


class ProfileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DataProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProfileInfoTournament(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MediaProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdvencedMediaProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SmallProfileInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DataProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DataProfile,
                    request_deserializer=profile__pb2.UserID.FromString,
                    response_serializer=profile__pb2.ProfileData.SerializeToString,
            ),
            'CreateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProfile,
                    request_deserializer=profile__pb2.CreateProfileData.FromString,
                    response_serializer=profile__pb2.SuccessProfile.SerializeToString,
            ),
            'ProfileInfoTournament': grpc.unary_unary_rpc_method_handler(
                    servicer.ProfileInfoTournament,
                    request_deserializer=profile__pb2.UserID.FromString,
                    response_serializer=profile__pb2.ProfileInfo.SerializeToString,
            ),
            'MediaProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.MediaProfile,
                    request_deserializer=profile__pb2.RequestMediaProfile.FromString,
                    response_serializer=profile__pb2.SuccessProfile.SerializeToString,
            ),
            'GetAdvencedMediaProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdvencedMediaProfile,
                    request_deserializer=profile__pb2.GetAdvencedMedia.FromString,
                    response_serializer=profile__pb2.AdvencedMediaData.SerializeToString,
            ),
            'SmallProfileInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SmallProfileInfo,
                    request_deserializer=profile__pb2.UserID.FromString,
                    response_serializer=profile__pb2.SmallRequstProfile.SerializeToString,
            ),
            'DeleteAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAccount,
                    request_deserializer=profile__pb2.UserID.FromString,
                    response_serializer=profile__pb2.SuccessProfile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'profile.Profile', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('profile.Profile', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Profile(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DataProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.Profile/DataProfile',
            profile__pb2.UserID.SerializeToString,
            profile__pb2.ProfileData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.Profile/CreateProfile',
            profile__pb2.CreateProfileData.SerializeToString,
            profile__pb2.SuccessProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProfileInfoTournament(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.Profile/ProfileInfoTournament',
            profile__pb2.UserID.SerializeToString,
            profile__pb2.ProfileInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MediaProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.Profile/MediaProfile',
            profile__pb2.RequestMediaProfile.SerializeToString,
            profile__pb2.SuccessProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAdvencedMediaProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.Profile/GetAdvencedMediaProfile',
            profile__pb2.GetAdvencedMedia.SerializeToString,
            profile__pb2.AdvencedMediaData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SmallProfileInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.Profile/SmallProfileInfo',
            profile__pb2.UserID.SerializeToString,
            profile__pb2.SmallRequstProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.Profile/DeleteAccount',
            profile__pb2.UserID.SerializeToString,
            profile__pb2.SuccessProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
