# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import challenge_pb2 as challenge__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in challenge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceChallengeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChallengeId = channel.unary_unary(
                '/challenge.ServiceChallenge/GetChallengeId',
                request_serializer=challenge__pb2.RequestReceipt.SerializeToString,
                response_deserializer=challenge__pb2.ResponseChallengeId.FromString,
                _registered_method=True)
        self.GetInfoId = channel.unary_unary(
                '/challenge.ServiceChallenge/GetInfoId',
                request_serializer=challenge__pb2.ResponseChallengeId.SerializeToString,
                response_deserializer=challenge__pb2.GetInfo.FromString,
                _registered_method=True)
        self.GetChallenges = channel.unary_unary(
                '/challenge.ServiceChallenge/GetChallenges',
                request_serializer=challenge__pb2.ResponseChallengeId.SerializeToString,
                response_deserializer=challenge__pb2.Challenges.FromString,
                _registered_method=True)
        self.ProgressInfo = channel.unary_unary(
                '/challenge.ServiceChallenge/ProgressInfo',
                request_serializer=challenge__pb2.UserID.SerializeToString,
                response_deserializer=challenge__pb2.HistoryInfo.FromString,
                _registered_method=True)
        self.WeekProgressInfo = channel.unary_unary(
                '/challenge.ServiceChallenge/WeekProgressInfo',
                request_serializer=challenge__pb2.User.SerializeToString,
                response_deserializer=challenge__pb2.WeekHistory.FromString,
                _registered_method=True)


class ServiceChallengeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetChallengeId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInfoId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChallenges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProgressInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WeekProgressInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceChallengeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChallengeId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChallengeId,
                    request_deserializer=challenge__pb2.RequestReceipt.FromString,
                    response_serializer=challenge__pb2.ResponseChallengeId.SerializeToString,
            ),
            'GetInfoId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfoId,
                    request_deserializer=challenge__pb2.ResponseChallengeId.FromString,
                    response_serializer=challenge__pb2.GetInfo.SerializeToString,
            ),
            'GetChallenges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChallenges,
                    request_deserializer=challenge__pb2.ResponseChallengeId.FromString,
                    response_serializer=challenge__pb2.Challenges.SerializeToString,
            ),
            'ProgressInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.ProgressInfo,
                    request_deserializer=challenge__pb2.UserID.FromString,
                    response_serializer=challenge__pb2.HistoryInfo.SerializeToString,
            ),
            'WeekProgressInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.WeekProgressInfo,
                    request_deserializer=challenge__pb2.User.FromString,
                    response_serializer=challenge__pb2.WeekHistory.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'challenge.ServiceChallenge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('challenge.ServiceChallenge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceChallenge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetChallengeId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/challenge.ServiceChallenge/GetChallengeId',
            challenge__pb2.RequestReceipt.SerializeToString,
            challenge__pb2.ResponseChallengeId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInfoId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/challenge.ServiceChallenge/GetInfoId',
            challenge__pb2.ResponseChallengeId.SerializeToString,
            challenge__pb2.GetInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChallenges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/challenge.ServiceChallenge/GetChallenges',
            challenge__pb2.ResponseChallengeId.SerializeToString,
            challenge__pb2.Challenges.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProgressInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/challenge.ServiceChallenge/ProgressInfo',
            challenge__pb2.UserID.SerializeToString,
            challenge__pb2.HistoryInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WeekProgressInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/challenge.ServiceChallenge/WeekProgressInfo',
            challenge__pb2.User.SerializeToString,
            challenge__pb2.WeekHistory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
