# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: challenge.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'challenge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63hallenge.proto\x12\tchallenge\"C\n\x0eRequestReceipt\x12\x18\n\x10sport_type_title\x18\x01 \x01(\t\x12\x17\n\x0f\x63hallange_title\x18\x02 \x01(\t\"!\n\x13ResponseChallengeId\x12\n\n\x02id\x18\x01 \x01(\x05\"7\n\x07GetInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05photo\x18\x02 \x01(\t\x12\x0f\n\x07\x63v_name\x18\x03 \x01(\t\"O\n\nChallenges\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05photo\x18\x02 \x01(\t\x12\x0f\n\x07\x63v_name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\")\n\x06UserID\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0e\n\x06period\x18\x02 \x01(\t\"3\n\x0bHistoryInfo\x12\x12\n\nchallenges\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61lories\x18\x02 \x01(\x05\"\x17\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"j\n\x0bWeekHistory\x12.\n\x04\x64\x61ys\x18\x01 \x03(\x0b\x32 .challenge.WeekHistory.DaysEntry\x1a+\n\tDaysEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\xe0\x02\n\x10ServiceChallenge\x12K\n\x0eGetChallengeId\x12\x19.challenge.RequestReceipt\x1a\x1e.challenge.ResponseChallengeId\x12?\n\tGetInfoId\x12\x1e.challenge.ResponseChallengeId\x1a\x12.challenge.GetInfo\x12\x46\n\rGetChallenges\x12\x1e.challenge.ResponseChallengeId\x1a\x15.challenge.Challenges\x12\x39\n\x0cProgressInfo\x12\x11.challenge.UserID\x1a\x16.challenge.HistoryInfo\x12;\n\x10WeekProgressInfo\x12\x0f.challenge.User\x1a\x16.challenge.WeekHistoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'challenge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEEKHISTORY_DAYSENTRY']._loaded_options = None
  _globals['_WEEKHISTORY_DAYSENTRY']._serialized_options = b'8\001'
  _globals['_REQUESTRECEIPT']._serialized_start=30
  _globals['_REQUESTRECEIPT']._serialized_end=97
  _globals['_RESPONSECHALLENGEID']._serialized_start=99
  _globals['_RESPONSECHALLENGEID']._serialized_end=132
  _globals['_GETINFO']._serialized_start=134
  _globals['_GETINFO']._serialized_end=189
  _globals['_CHALLENGES']._serialized_start=191
  _globals['_CHALLENGES']._serialized_end=270
  _globals['_USERID']._serialized_start=272
  _globals['_USERID']._serialized_end=313
  _globals['_HISTORYINFO']._serialized_start=315
  _globals['_HISTORYINFO']._serialized_end=366
  _globals['_USER']._serialized_start=368
  _globals['_USER']._serialized_end=391
  _globals['_WEEKHISTORY']._serialized_start=393
  _globals['_WEEKHISTORY']._serialized_end=499
  _globals['_WEEKHISTORY_DAYSENTRY']._serialized_start=456
  _globals['_WEEKHISTORY_DAYSENTRY']._serialized_end=499
  _globals['_SERVICECHALLENGE']._serialized_start=502
  _globals['_SERVICECHALLENGE']._serialized_end=854
# @@protoc_insertion_point(module_scope)
